import type { AppData, AppSettings } from "@/types/domain";

export const defaultSettings: AppSettings = {
  id: "default",
  profileNames: {
    mine: "Io",
    partner: "Lei",
  },
  sharedRatio: {
    mine: 50,
    partner: 50,
  },
  currency: "EUR",
};

export const defaultCategories = [
  { name: "Casa", color: "#2563eb", icon: "house" },
  { name: "Utenze", color: "#0891b2", icon: "plug" },
  { name: "Mobilita", color: "#16a34a", icon: "car" },
  { name: "Abbonamenti", color: "#7c3aed", icon: "tv" },
  { name: "Salute", color: "#dc2626", icon: "heartPulse" },
  { name: "Altro", color: "#64748b", icon: "receipt" },
];

const now = new Date().toISOString();

export const demoData: AppData = {
  settings: defaultSettings,
  categories: defaultCategories.map((category, index) => ({
    id: `demo-category-${index + 1}`,
    name: category.name,
    color: category.color,
    createdAt: now,
    updatedAt: now,
  })),
  incomes: [
    {
      id: "demo-income-1",
      name: "Stipendio principale",
      description: "Entrata mensile di esempio",
      owner: "mine",
      monthlyAmountCents: 220000,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-income-2",
      name: "Stipendio partner",
      description: "Entrata mensile di esempio",
      owner: "partner",
      monthlyAmountCents: 190000,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  expenses: [
    {
      id: "demo-expense-1",
      name: "Affitto",
      description: "Spesa mensile condivisa",
      categoryId: "demo-category-1",
      owner: "shared",
      amountCents: 85000,
      recurrence: "monthly",
      firstDueDate: "2026-05-05",
      dueDayOfMonth: 5,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-expense-2",
      name: "Spesa alimentare fissa",
      description: "Budget settimanale fisso",
      categoryId: "demo-category-6",
      owner: "shared",
      amountCents: 9000,
      recurrence: "weekly",
      firstDueDate: "2026-05-23",
      weekday: 6,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-expense-3",
      name: "Streaming",
      description: "Abbonamento mensile",
      categoryId: "demo-category-4",
      owner: "mine",
      amountCents: 1299,
      recurrence: "monthly",
      firstDueDate: "2026-05-18",
      dueDayOfMonth: 18,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  loans: [
    {
      id: "demo-loan-1",
      name: "Finanziamento auto",
      description: "Esempio di rateazione attiva",
      owner: "shared",
      paymentCents: 24500,
      paymentDayOfMonth: 15,
      firstPaymentDate: "2024-01-15",
      totalInstallments: 60,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  investments: [
    {
      id: "demo-investment-1",
      name: "ETF globale",
      owner: "mine",
      initialAmountCents: 500000,
      startDate: "2025-01-10",
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-investment-2",
      name: "Fondo emergenza investito",
      owner: "shared",
      initialAmountCents: 250000,
      startDate: "2025-09-01",
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  investmentTrackings: [
    {
      id: "demo-investment-tracking-1",
      investmentId: "demo-investment-1",
      movementCents: 100000,
      currentValueCents: 630000,
      trackedAt: "2025-07-10",
      note: "Primo versamento extra",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-investment-tracking-2",
      investmentId: "demo-investment-1",
      movementCents: 50000,
      currentValueCents: 710000,
      trackedAt: "2026-05-01",
      note: "Aggiornamento valore",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo-investment-tracking-3",
      investmentId: "demo-investment-2",
      movementCents: 75000,
      currentValueCents: 338000,
      trackedAt: "2026-04-15",
      createdAt: now,
      updatedAt: now,
    },
  ],
  cashBalances: [
    {
      id: "demo-cash-1",
      owner: "mine",
      balanceCents: 12000,
      asOfDate: "2026-05-20",
      updatedAt: now,
    },
    {
      id: "demo-cash-2",
      owner: "partner",
      balanceCents: 8500,
      asOfDate: "2026-05-20",
      updatedAt: now,
    },
    {
      id: "demo-cash-3",
      owner: "shared",
      balanceCents: 5000,
      asOfDate: "2026-05-20",
      updatedAt: now,
    },
  ],
};
